### ISSUE TITLE
Search in Launcher

### ISSUE THREAD

**Issue by PhilipLeddin** [sprinteins/oscd-launcher#5]
As a user I want to search for specific plugins to be able to find them quickly.

- [x] there is a text-search to find plugins based on their names
- [x] when searching the page of plugins will be reduced to fitting ones
- [x] i can click on the found plugins to open them

**Comment by PhilipLeddin** [comment]
![Image](https://github.com/user-attachments/assets/8128c4a8-26fe-484a-b0c6-d43ee7cbdec8)

**Comment by michelguerin** [comment]
For now, we are able to enable/disable plugins from the launcher. Instantiation and focus will be done in another US.
